# The URL the site will be built for
base_url = "https://blog.digitalsorcery.net"
compile_sass = true
highlight_code = true
build_search_index = false

title = "Blog"
theme="hyde"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "https://google.com", name = "About"},
]
