# The URL the site will be built for
base_url = "https://blog.digitalsorcery.net"
compile_sass = true
highlight_code = true
build_search_index = false

title = "Blog"
theme="hyde"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/about.html", name = "About", icon="fas fa-id-badge"},
    {url = "/blog", name = "Blog", icon="fas fa-pencil-alt"},
    {url = "/resume.html", name = "Resume", icon="fas fa-file"},
    {url = "https://twitter.com/digitalsorcery", name = "@digitalsorcery", icon="fab fa-twitter"},
    {url = "#?", name = "Feed", icon="fas fa-rss"},
    {url = "#?", name = "Email", icon="fas fa-at"},
    
]
