# The URL the site will be built for
base_url = "https://blog.digitalsorcery.net"
compile_sass = true
highlight_code = true
build_search_index = false
generate_rss = true
title = "Blog"
description = "description"
#theme="hyde"

# build_timestamp = set by zola. Could be used for improved auto refresh

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/about", name = "About", icon="fas fa-id-badge"},
    {url = "/blog", name = "Blog", icon="fas fa-pencil-alt"},
    {url = "/resume", name = "Resume", icon="fas fa-file"},
    {url = "https://twitter.com/digitalsorcery", name = "@digitalsorcery", icon="fab fa-twitter"},
    {url = "#?", name = "Feed", icon="fas fa-rss"},
    {url = "mailto:eric@digitalsorcery.net", name = "Email", icon="fas fa-at"},
    
]
